# Generated by Django 6.0.1 on 2026-01-17 05:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservation",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="reservation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="room",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("occupied", "Occupied"),
                    ("cleaning", "Cleaning/Maintenance"),
                    ("blocked", "Blocked"),
                ],
                default="available",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("confirmed", "Confirmed"),
                    ("checked_in", "Checked In"),
                    ("checked_out", "Checked Out"),
                    ("cancelled", "Cancelled"),
                    ("no_show", "No-Show"),
                ],
                default="confirmed",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["room", "status", "check_in"],
                name="reservation_room_id_fdf8f8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["guest", "status"], name="reservation_guest_i_e2d423_idx"
            ),
        ),
    ]
