# Generated by Django 6.0.1 on 2026-01-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reservations",
            "0002_alter_reservation_options_reservation_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="total_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total price calculated when reservation is confirmed",
                max_digits=10,
                null=True,
            ),
        ),
    ]
